version: '2'
services:
    db:
        image: mongo
        ports:
            - 27017:27017
        restart: unless-stopped
        
    quiz-server:
        build: .
        depends_on:
            - db
        ports:
            - 5000:5000
        environment:
            - MONGODB_URI=mongodb://db:27017/quiz
        restart: unless-stopped
        
    quiz-master-client:
        build: ./quiz-master-client
        depends_on:
            - quiz-server
        ports:
            - 3000:80
        restart: unless-stopped
      
    quiz-participant-client:
        build: ./quiz-participant-client
        depends_on:
            - quiz-server
        ports:
            - 3001:80
        restart: unless-stopped
