CREATE TABLE IF NOT EXISTS EVENT_ENTITY (
    ID SERIAL PRIMARY KEY,
    AGGREGATE_ID VARCHAR(255),
    TYPE VARCHAR(255),
    CREATED_AT TIMESTAMP,
    DOMAIN_EVENT VARCHAR(4096)
);
CREATE INDEX IF NOT EXISTS AGGREGATE_ID_INDEX ON EVENT_ENTITY (AGGREGATE_ID);
CREATE INDEX IF NOT EXISTS CREATED_AT_INDEX ON EVENT_ENTITY (CREATED_AT);


ALTER TABLE EVENT_ENTITY ADD COLUMN IF NOT EXISTS SEQUENCE_NUMBER INT DEFAULT -1;
CREATE INDEX IF NOT EXISTS SEQUENCE_NUMBER_INDEX ON EVENT_ENTITY (SEQUENCE_NUMBER);


DROP INDEX SEQUENCE_NUMBER_INDEX ON EVENT_ENTITY;
ALTER TABLE EVENT_ENTITY DROP COLUMN SEQUENCE_NUMBER;
ALTER TABLE EVENT_ENTITY ADD COLUMN IF NOT EXISTS SEQUENCE_NUMBER BIGINT DEFAULT -1;
CREATE INDEX IF NOT EXISTS SEQUENCE_NUMBER_INDEX ON EVENT_ENTITY (SEQUENCE_NUMBER);
