CREATE TABLE QUIZ_ENTITY (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255),
    MODERATOR_PASSWORD VARCHAR(255),
    PARTICIPANT_PASSWORD VARCHAR(255)
);

CREATE TABLE PARTICIPANT_ENTITY (
    ID SERIAL PRIMARY KEY,
    NAME VARCHAR(255),
    TURN INT,
    POINTS INT,
    QUIZ_ID INT,
    FOREIGN KEY(QUIZ_ID) REFERENCES QUIZ_ENTITY(ID)
);

CREATE TABLE QUESTION_ENTITY (
    ID SERIAL PRIMARY KEY,
    QUESTION VARCHAR(255),
    PENDING INT,
    QUIZ_ID INT,
    FOREIGN KEY(QUIZ_ID) REFERENCES QUIZ_ENTITY(ID)
);
